name: Build and lint

on:
  pull_request:
    branches: [master]

env:
  IMAGE_NAME: bitcollector-bot

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn

    - name: Lint
      run: yarn lint
    
    - name: Build project
      run: yarn build